from fpdf import FPDF
import google.genai.types as types
from google.adk.tools import ToolContext


def _safe(text: str) -> str:
    """Replace characters outside latin-1 range with safe ASCII equivalents."""
    return (
        text
        .replace("\u2014", "-")   # em dash
        .replace("\u2013", "-")   # en dash
        .replace("\u2022", "-")   # bullet
        .replace("\u2018", "'")   # left single quote
        .replace("\u2019", "'")   # right single quote
        .replace("\u201c", '"')   # left double quote
        .replace("\u201d", '"')   # right double quote
        .encode("latin-1", errors="replace")
        .decode("latin-1")
    )


def _build_pdf(title: str, sections: list[dict]) -> bytes:
    """Builds a PDF in memory and returns raw bytes."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_fill_color(30, 80, 160)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 14, _safe(title), new_x="LMARGIN", new_y="NEXT", align="C", fill=True)
    pdf.ln(6)

    for section in sections:
        # Section heading
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 80, 160)
        pdf.set_fill_color(220, 230, 245)
        pdf.cell(0, 9, _safe(section["heading"]), new_x="LMARGIN", new_y="NEXT", fill=True)
        pdf.ln(2)

        # Section body
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(30, 30, 30)
        page_w = pdf.w - pdf.l_margin - pdf.r_margin
        for line in section["lines"]:
            safe_line = _safe(line)
            if safe_line.startswith("-"):
                indent = 5
                pdf.set_x(pdf.l_margin + indent)
                pdf.multi_cell(page_w - indent, 7, safe_line)
            else:
                pdf.multi_cell(page_w, 7, safe_line)
        pdf.ln(3)

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 8, "Generated by Insurance Support Agent - for informational purposes only.", align="C")

    return bytes(pdf.output())


async def generate_insurance_summary_pdf(
    insurance_type: str,
    tool_context: ToolContext,
) -> dict:
    """
    Generates a PDF summary guide for a given insurance type and saves it as an artifact.
    Use this when the user asks for a downloadable guide, summary, or reference document
    about an insurance topic.

    Args:
        insurance_type (str): The type of insurance to generate a guide for.
                              E.g. 'health', 'auto', 'home', 'life', 'travel'.

    Returns:
        dict: Status and the artifact filename where the PDF was saved.
    """
    guides = {
        "health": {
            "title": "Health Insurance - Complete Guide",
            "sections": [
                {
                    "heading": "What is Health Insurance?",
                    "lines": [
                        "Health insurance covers medical expenses including doctor visits,",
                        "hospital stays, surgeries, prescription drugs, and preventive care.",
                    ],
                },
                {
                    "heading": "Key Terms",
                    "lines": [
                        "• Premium: Your monthly payment to keep the policy active.",
                        "• Deductible: Amount you pay before insurance kicks in.",
                        "• Copay: Fixed fee per visit (e.g. $20 for a doctor visit).",
                        "• Coinsurance: Your share after deductible (e.g. 20% of costs).",
                        "• Out-of-Pocket Maximum: The most you'll pay in a year.",
                        "• Network: Doctors/hospitals that have agreements with your insurer.",
                    ],
                },
                {
                    "heading": "Plan Types",
                    "lines": [
                        "• HMO (Health Maintenance Organization): Requires referrals, lower cost.",
                        "• PPO (Preferred Provider Organization): More flexibility, higher cost.",
                        "• EPO: Like PPO but no out-of-network coverage.",
                        "• HDHP (High Deductible Health Plan): Paired with HSA savings account.",
                    ],
                },
                {
                    "heading": "Tips for Choosing a Plan",
                    "lines": [
                        "• Check if your current doctors are in-network.",
                        "• Estimate your yearly medical usage before picking a deductible.",
                        "• Consider an HDHP + HSA if you're generally healthy.",
                        "• Always check prescription drug coverage.",
                    ],
                },
            ],
        },
        "auto": {
            "title": "Auto Insurance - Complete Guide",
            "sections": [
                {
                    "heading": "What is Auto Insurance?",
                    "lines": [
                        "Auto insurance protects you financially in case of accidents,",
                        "theft, or damage to your vehicle or others' property.",
                    ],
                },
                {
                    "heading": "Coverage Types",
                    "lines": [
                        "• Liability: Covers damage/injury you cause to others. Usually required by law.",
                        "• Collision: Covers your car damage in an accident regardless of fault.",
                        "• Comprehensive: Covers theft, weather, fire, animal damage.",
                        "• Uninsured Motorist: Protects you if hit by an uninsured driver.",
                        "• PIP / Medical Payments: Covers medical costs for you and passengers.",
                    ],
                },
                {
                    "heading": "What Affects Your Premium?",
                    "lines": [
                        "• Your driving record (accidents, tickets)",
                        "• Age and experience",
                        "• Vehicle make, model, and year",
                        "• Where you live and park",
                        "• Annual mileage",
                        "• Credit score (in most states)",
                    ],
                },
                {
                    "heading": "Tips",
                    "lines": [
                        "• Bundle auto + home insurance for discounts.",
                        "• Raise your deductible to lower premiums.",
                        "• Ask about safe driver, good student, or low-mileage discounts.",
                    ],
                },
            ],
        },
        "home": {
            "title": "Home Insurance - Complete Guide",
            "sections": [
                {
                    "heading": "What is Home Insurance?",
                    "lines": [
                        "Home insurance protects your home's structure and personal belongings",
                        "and provides liability coverage if someone is injured on your property.",
                    ],
                },
                {
                    "heading": "What's Covered",
                    "lines": [
                        "• Dwelling: The physical structure of your home.",
                        "• Other Structures: Garages, fences, sheds.",
                        "• Personal Property: Furniture, electronics, clothing.",
                        "• Liability: Legal costs if someone is hurt on your property.",
                        "• Additional Living Expenses: Temporary housing if home is uninhabitable.",
                    ],
                },
                {
                    "heading": "What's NOT Covered",
                    "lines": [
                        "• Floods - requires a separate flood insurance policy.",
                        "• Earthquakes - requires a separate earthquake policy.",
                        "• Normal wear and tear.",
                        "• Pest/insect damage.",
                    ],
                },
                {
                    "heading": "Tips",
                    "lines": [
                        "• Keep a home inventory with photos and receipts.",
                        "• Review your policy limits annually.",
                        "• Consider replacement cost vs. actual cash value coverage.",
                    ],
                },
            ],
        },
        "life": {
            "title": "Life Insurance - Complete Guide",
            "sections": [
                {
                    "heading": "What is Life Insurance?",
                    "lines": [
                        "Life insurance pays a benefit to your beneficiaries when you pass away,",
                        "helping replace income and cover expenses like mortgage and education.",
                    ],
                },
                {
                    "heading": "Types of Life Insurance",
                    "lines": [
                        "• Term Life: Coverage for a set period (10-30 years). Most affordable.",
                        "• Whole Life: Permanent coverage with a cash value component.",
                        "• Universal Life: Flexible premiums and death benefits.",
                        "• Variable Life: Tied to investment accounts, higher risk/reward.",
                    ],
                },
                {
                    "heading": "How Much Coverage Do You Need?",
                    "lines": [
                        "• Common rule: 10-12x your annual income.",
                        "• Factor in: mortgage, debts, childcare, education costs.",
                        "• Online calculators can give a more precise number.",
                    ],
                },
                {
                    "heading": "Tips",
                    "lines": [
                        "• Buy early - premiums are much lower when you're young and healthy.",
                        "• Review and update beneficiaries after life events.",
                        "• Term life is usually the best starting point for most families.",
                    ],
                },
            ],
        },
        "travel": {
            "title": "Travel Insurance - Complete Guide",
            "sections": [
                {
                    "heading": "What is Travel Insurance?",
                    "lines": [
                        "Travel insurance protects you from financial losses while traveling,",
                        "including trip cancellations, medical emergencies, and lost luggage.",
                    ],
                },
                {
                    "heading": "What's Typically Covered",
                    "lines": [
                        "• Trip cancellation / interruption",
                        "• Emergency medical expenses abroad",
                        "• Medical evacuation",
                        "• Lost, stolen, or delayed baggage",
                        "• Travel delay reimbursement",
                        "• Accidental death & dismemberment",
                    ],
                },
                {
                    "heading": "When You Need It Most",
                    "lines": [
                        "• International travel where your health plan doesn't apply.",
                        "• Expensive non-refundable trips.",
                        "• Travel to regions with political instability or health risks.",
                    ],
                },
                {
                    "heading": "Tips",
                    "lines": [
                        "• Buy travel insurance immediately after booking your trip.",
                        "• Check if your credit card already provides travel coverage.",
                        "• Read the fine print on 'cancel for any reason' clauses.",
                    ],
                },
            ],
        },
    }

    key = insurance_type.lower().strip()
    # fuzzy match
    matched = None
    for k in guides:
        if key in k or k in key:
            matched = k
            break

    if not matched:
        return {
            "status": "error",
            "message": f"No guide available for '{insurance_type}'. Try: health, auto, home, life, travel.",
        }

    guide = guides[matched]
    pdf_bytes = _build_pdf(guide["title"], guide["sections"])

    artifact = types.Part.from_bytes(data=pdf_bytes, mime_type="application/pdf")
    filename = f"{matched}_insurance_guide.pdf"
    version = await tool_context.save_artifact(filename=filename, artifact=artifact)

    return {
        "status": "success",
        "message": f"PDF guide generated and saved.",
        "filename": filename,
        "version": version,
        "size_bytes": len(pdf_bytes),
        "instruction": f"Tell the user their '{guide['title']}' PDF is ready and available as artifact '{filename}'.",
    }
